CREATE TABLE devices (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    machine_hash CHAR(64) NOT NULL UNIQUE
        CHECK (machine_hash ~ '^[0-9a-f]{64}$'),
    name TEXT NOT NULL DEFAULT '',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    device_id UUID NOT NULL REFERENCES devices(id),
    username TEXT NOT NULL,
    password_salt TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('admin', 'operator')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX users_username_ci_unique
    ON users (lower(username));

CREATE TABLE serial_counter (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    device_id UUID NOT NULL UNIQUE REFERENCES devices(id),
    serial_number TEXT NOT NULL,
    serial_count TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX serial_counter_serial_number_unique
    ON serial_counter (upper(btrim(serial_number)));

CREATE TABLE dummy_log (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    device_id UUID NOT NULL REFERENCES devices(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    sl_no BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    date TEXT NOT NULL DEFAULT '',
    time TEXT NOT NULL DEFAULT '',
    serial_count TEXT NOT NULL DEFAULT '',
    serial_number TEXT NOT NULL DEFAULT '',
    ref_no TEXT NOT NULL DEFAULT '',
    variant TEXT NOT NULL DEFAULT '',
    m1 TEXT NOT NULL DEFAULT '',
    m2 TEXT NOT NULL DEFAULT '',
    m3 TEXT NOT NULL DEFAULT '',
    m4 TEXT NOT NULL DEFAULT '',
    dummy_pack_status TEXT NOT NULL DEFAULT '',
    dummy_pack_qr TEXT NOT NULL DEFAULT '',
    issue_desc_1 TEXT NOT NULL DEFAULT '',
    issue_desc_2 TEXT NOT NULL DEFAULT '',
    action_plan TEXT NOT NULL DEFAULT '',
    remark TEXT NOT NULL DEFAULT '',
    admin_ack TEXT NOT NULL DEFAULT ''
);

CREATE UNIQUE INDEX dummy_log_serial_number_unique
    ON dummy_log (upper(btrim(serial_number)))
    WHERE btrim(serial_number) <> '';

CREATE UNIQUE INDEX dummy_log_m1_unique ON dummy_log (upper(btrim(m1))) WHERE btrim(m1) <> '';
CREATE UNIQUE INDEX dummy_log_m2_unique ON dummy_log (upper(btrim(m2))) WHERE btrim(m2) <> '';
CREATE UNIQUE INDEX dummy_log_m3_unique ON dummy_log (upper(btrim(m3))) WHERE btrim(m3) <> '';
CREATE UNIQUE INDEX dummy_log_m4_unique ON dummy_log (upper(btrim(m4))) WHERE btrim(m4) <> '';

CREATE FUNCTION reject_duplicate_dummy_module_ids() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    new_modules TEXT[] := array_remove(
        ARRAY[upper(btrim(NEW.m1)), upper(btrim(NEW.m2)), upper(btrim(NEW.m3)), upper(btrim(NEW.m4))],
        ''
    );
BEGIN
    PERFORM pg_advisory_xact_lock(791204611);

    IF cardinality(new_modules) <> (
        SELECT count(DISTINCT module_id)
        FROM unnest(new_modules) AS module_values(module_id)
    ) THEN
        RAISE EXCEPTION 'Module IDs must be unique within a dummy record'
            USING ERRCODE = '23505';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM dummy_log AS existing
        CROSS JOIN LATERAL unnest(
            ARRAY[
                upper(btrim(existing.m1)), upper(btrim(existing.m2)),
                upper(btrim(existing.m3)), upper(btrim(existing.m4))
            ]
        ) AS existing_module(module_id)
        JOIN unnest(new_modules) AS new_module(module_id)
            ON new_module.module_id = existing_module.module_id
        WHERE existing.id IS DISTINCT FROM NEW.id
    ) THEN
        RAISE EXCEPTION 'Module IDs must be unique across dummy records'
            USING ERRCODE = '23505';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER dummy_log_module_ids_unique
    BEFORE INSERT OR UPDATE OF m1, m2, m3, m4 ON dummy_log
    FOR EACH ROW EXECUTE FUNCTION reject_duplicate_dummy_module_ids();

CREATE TABLE pack_id_log (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    device_id UUID NOT NULL REFERENCES devices(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    sl_no BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    date TEXT NOT NULL DEFAULT '',
    time TEXT NOT NULL DEFAULT '',
    serial_number TEXT NOT NULL DEFAULT '',
    variant TEXT NOT NULL DEFAULT '',
    pack_qr_data TEXT NOT NULL DEFAULT ''
);

CREATE UNIQUE INDEX pack_id_log_serial_number_unique
    ON pack_id_log (upper(btrim(serial_number)))
    WHERE btrim(serial_number) <> '';

CREATE TABLE bms_log (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    device_id UUID NOT NULL REFERENCES devices(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    sl_no BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    date TEXT NOT NULL DEFAULT '',
    time TEXT NOT NULL DEFAULT '',
    pack_qr_data TEXT NOT NULL DEFAULT '',
    bmb_id TEXT NOT NULL DEFAULT '',
    cmb_id TEXT NOT NULL DEFAULT '',
    rework_bmb_id TEXT NOT NULL DEFAULT '',
    rework_cmb_id TEXT NOT NULL DEFAULT ''
);

CREATE UNIQUE INDEX bms_log_bmb_id_unique
    ON bms_log (upper(btrim(bmb_id))) WHERE btrim(bmb_id) <> '';
CREATE UNIQUE INDEX bms_log_cmb_id_unique
    ON bms_log (upper(btrim(cmb_id))) WHERE btrim(cmb_id) <> '';
CREATE UNIQUE INDEX bms_log_rework_bmb_id_unique
    ON bms_log (upper(btrim(rework_bmb_id))) WHERE btrim(rework_bmb_id) <> '';
CREATE UNIQUE INDEX bms_log_rework_cmb_id_unique
    ON bms_log (upper(btrim(rework_cmb_id))) WHERE btrim(rework_cmb_id) <> '';

CREATE FUNCTION reject_duplicate_bms_ids() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    new_ids TEXT[] := array_remove(
        ARRAY[
            upper(btrim(NEW.bmb_id)), upper(btrim(NEW.cmb_id)),
            upper(btrim(NEW.rework_bmb_id)), upper(btrim(NEW.rework_cmb_id))
        ],
        ''
    );
BEGIN
    PERFORM pg_advisory_xact_lock(791204612);

    IF cardinality(new_ids) <> (
        SELECT count(DISTINCT bms_id)
        FROM unnest(new_ids) AS bms_values(bms_id)
    ) THEN
        RAISE EXCEPTION 'BMS IDs must be unique within a record'
            USING ERRCODE = '23505';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM bms_log AS existing
        CROSS JOIN LATERAL unnest(
            ARRAY[
                upper(btrim(existing.bmb_id)), upper(btrim(existing.cmb_id)),
                upper(btrim(existing.rework_bmb_id)), upper(btrim(existing.rework_cmb_id))
            ]
        ) AS existing_id(bms_id)
        JOIN unnest(new_ids) AS new_id(bms_id)
            ON new_id.bms_id = existing_id.bms_id
        WHERE existing.id IS DISTINCT FROM NEW.id
    ) THEN
        RAISE EXCEPTION 'BMS IDs must be unique across records'
            USING ERRCODE = '23505';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER bms_log_ids_unique
    BEFORE INSERT OR UPDATE OF bmb_id, cmb_id, rework_bmb_id, rework_cmb_id
    ON bms_log
    FOR EACH ROW EXECUTE FUNCTION reject_duplicate_bms_ids();

CREATE INDEX dummy_log_created_at_idx ON dummy_log (created_at DESC);
CREATE INDEX pack_id_log_created_at_idx ON pack_id_log (created_at DESC);
CREATE INDEX bms_log_created_at_idx ON bms_log (created_at DESC);
