from __future__ import annotations

from common.nomenclature.serial_number import (
    CATEGORY_BY_CODE_NEW,
    CATEGORY_CODES_NEW,
    MODEL_BY_CODE,
    MODEL_CODES,
    NEW_PLANT_BY_CODE,
    NEW_PLANT_CODES,
    NEW_SERIAL_NUMBER_PATTERN,
    PLANT_BY_CODE,
    PLANT_CODES,
    SERIAL_NUMBER_PATTERN,
    SHIFT_CODES_NEW,
    VARIANT_BY_CODE_NEW,
    MODULE_VARIANT_CODES_NEW,
    ParsedSerialNumber,
    build_serial_number,
    build_serial_number_for_model,
    parse_serial_number,
)

__all__ = [
    "CATEGORY_BY_CODE_NEW",
    "CATEGORY_CODES_NEW",
    "MODEL_BY_CODE",
    "MODEL_CODES",
    "NEW_PLANT_BY_CODE",
    "NEW_PLANT_CODES",
    "NEW_SERIAL_NUMBER_PATTERN",
    "PLANT_BY_CODE",
    "PLANT_CODES",
    "SERIAL_NUMBER_PATTERN",
    "SHIFT_CODES_NEW",
    "VARIANT_BY_CODE_NEW",
    "MODULE_VARIANT_CODES_NEW",
    "ParsedSerialNumber",
    "build_serial_number",
    "build_serial_number_for_model",
    "parse_serial_number",
]